### ISSUE TITLE
logged out when renaming facility group

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#137] opened 2023-12-22 10:20 UTC
## Current behavior

https://jam.dev/c/3fadec84-29c4-4d63-9a7e-d41e1a63377c

**Comment by dt2patel** [comment] 2023-12-22 10:22
https://jam.dev/c/b080d1ef-f07c-49d9-81fa-4a59d35acda1

Tried again and was unable to rename facility.

**Comment by ravilodhi** [comment] 2023-12-26 06:11
Renaming Facility Group is working fine on dev-oms. The demo-oms instance is not on the latest, which is why API is not available on that instance hence failing the rename operation.

I am unable to reproduce the 'logged out' issue when renaming the facility group. It is possible that the token expires and redirects you to the login page. Marking it as closed as of now.

@dt2patel

**Closed by ravilodhi** 2023-12-26 06:11 UTC
Labels: bug
